[package]
name = "problem_backpack"
version = "0.1.0"
authors = ["adrian <adrian.f.castanedan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.13.0"
